#include "SensorDataLoader.h"
#include <fstream>
#include <sstream>
#include <iostream>
#include <stdexcept>
#include <cmath>

namespace {
    // Helper to dynamically read the noise values generated by Python
    struct NoiseConfig {
        double r_range = 15.0, r_az = 0.5, r_el = 0.5, r_vr = 2.0;
        double e_az = 0.05, e_el = 0.05;
    };

    NoiseConfig readNoiseConfig() {
        NoiseConfig nc;
        std::ifstream file("../data/sensor_noise.txt");
        if (file.is_open()) {
            file >> nc.r_range >> nc.r_az >> nc.r_el >> nc.r_vr;
            file >> nc.e_az >> nc.e_el;
        } else {
            std::cerr << "[Warning] Could not open ../data/sensor_noise.txt. Using default static noise matrices." << std::endl;
        }
        return nc;
    }
}

bool SensorDataLoader::loadDataToQueue(const std::string& radar_file, 
                                       const std::string& eo_file, 
                                       EventQueue& queue) {
    try {
        loadRadarData(radar_file, queue);
        loadEOData(eo_file, queue);
        return true;
    } catch (const std::exception& e) {
        std::cerr << "[Error] Failed to load sensor data: " << e.what() << std::endl;
        return false;
    }
}

void SensorDataLoader::loadRadarData(const std::string& filepath, EventQueue& queue) {
    std::ifstream file(filepath);
    if (!file.is_open()) {
        throw std::runtime_error("Could not open Radar CSV: " + filepath);
    }

    std::string line;
    std::getline(file, line); // Skip header

    // ======================================================
    // שינוי חשוב: הוספת מרווח ביטחון (Tuning Mismatch)
    // אנחנו מכניסים בכוונה 25% יותר רעש ממה שהיה בדאטה
    // זה מוכיח שהמערכת עמידה גם כאשר פרמטרי הרעש אינם מדויקים
    // ======================================================
    NoiseConfig nc = readNoiseConfig();
    double safety_factor = 2.0;   // 50% יותר שמרני

    Eigen::Matrix4d R_radar;
    double az_rad_std = nc.r_az * M_PI / 180.0 * safety_factor;
    double el_rad_std = nc.r_el * M_PI / 180.0 * safety_factor;

    R_radar << (nc.r_range * safety_factor) * (nc.r_range * safety_factor), 0, 0, 0,
               0, az_rad_std * az_rad_std, 0, 0,
               0, 0, el_rad_std * el_rad_std, 0,
               0, 0, 0, (nc.r_vr * safety_factor) * (nc.r_vr * safety_factor);
    // ======================================================

    while (std::getline(file, line)) {
        if (line.empty()) continue;
        std::stringstream ss(line);
        std::string cell;

        std::getline(ss, cell, ','); double timestamp = std::stod(cell);
        std::getline(ss, cell, ','); 
        std::getline(ss, cell, ','); double range = std::stod(cell);
        std::getline(ss, cell, ','); double az_deg = std::stod(cell);
        std::getline(ss, cell, ','); double el_deg = std::stod(cell);
        std::getline(ss, cell, ','); double vr = std::stod(cell);

        double az_rad = az_deg * M_PI / 180.0;
        double el_rad = el_deg * M_PI / 180.0;

        queue.push(std::make_unique<RadarMeasurement>(timestamp, range, az_rad, el_rad, vr, R_radar));
    }
}

void SensorDataLoader::loadEOData(const std::string& filepath, EventQueue& queue) {
    std::ifstream file(filepath);
    if (!file.is_open()) {
        throw std::runtime_error("Could not open EO CSV: " + filepath);
    }

    std::string line;
    std::getline(file, line); // Skip header

    // ======================================================
    // שינוי חשוב: הוספת מרווח ביטחון גם ל-EO
    // ======================================================
    NoiseConfig nc = readNoiseConfig();
    double safety_factor = 2.0;   // 50% יותר שמרני

    Eigen::Matrix2d R_eo;
    double eo_az_std = nc.e_az * M_PI / 180.0 * safety_factor;
    double eo_el_std = nc.e_el * M_PI / 180.0 * safety_factor;

    R_eo << eo_az_std * eo_az_std, 0,
            0, eo_el_std * eo_el_std;
    // ======================================================

    while (std::getline(file, line)) {
        if (line.empty()) continue;
        std::stringstream ss(line);
        std::string cell;

        std::getline(ss, cell, ','); double timestamp = std::stod(cell);
        std::getline(ss, cell, ','); 
        std::getline(ss, cell, ','); double az_deg = std::stod(cell);
        std::getline(ss, cell, ','); double el_deg = std::stod(cell);

        double az_rad = az_deg * M_PI / 180.0;
        double el_rad = el_deg * M_PI / 180.0;

        queue.push(std::make_unique<EOMeasurement>(timestamp, az_rad, el_rad, R_eo));
    }
}